services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    depends_on:
      - mongo
